-- 0037_drop_redundant_prompt_hash_idx.sql
--
-- Drops the redundant single-column index idx_token_events_prompt_hash from
-- the token_events partitioned table.
--
-- WHY IT IS REDUNDANT:
--   Migration 0034 created two indexes on token_events.prompt_hash:
--
--     idx_token_events_prompt_hash   ON token_events (prompt_hash)
--     idx_token_events_prompt_hash2  ON token_events (prompt_hash, created_at DESC)
--                                    WHERE prompt_text != ''
--
--   Any query that can use idx_token_events_prompt_hash (equality or range on
--   prompt_hash) is also satisfied by the leading column of
--   idx_token_events_prompt_hash2.  Postgres will choose the composite index
--   for cache-warmer JOIN lookups and any other prompt_hash filter because it
--   covers more columns.  The single-column index is never chosen by the
--   planner and only adds write amplification on every INSERT across all 8
--   partitions.
--
-- SAFE TO RUN:
--   A partitioned (parent) index CANNOT be dropped CONCURRENTLY — Postgres
--   rejects it outright ("cannot drop partitioned index ... concurrently").
--   This file originally used DROP INDEX CONCURRENTLY and therefore failed on
--   every database where 0034 had partitioned token_events; no database ever
--   recorded it as applied (#125). The plain DROP below removes the parent
--   index and all 8 child partition indexes in one fast catalog-only
--   statement. It takes a brief ACCESS EXCLUSIVE lock on token_events and its
--   partitions — irrelevant on a fresh database; on a live one, set a
--   lock_timeout and retry rather than queueing behind long transactions.
--   Plain DROP INDEX is transaction-safe, so this migration runs on the
--   default atomic path (SQL + schema_migrations record in one transaction).

DROP INDEX IF EXISTS idx_token_events_prompt_hash;
