apiVersion: v1
kind: Service
metadata:
  name: {{ include "lens.fullname" . }}
  labels:
    {{- include "lens.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "lens.componentSelectorLabels" (list . "gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
